#!/bin/bash
# Process the per-message-size latency numbers generated by clusterperf.py,
# output the data points used to plot the slowdown graph.
#
# Caveat: the min. latency number is obtained from the same experiment,
# which is larger than true min. latency number in a empty network.
#
# Usage: genSlowdownDatapoints inFile workloadId loadFactor

cperfOutput=$1
workload=$2
loadFactor=$3
numMessages=$(awk '$1~/^[0-9]+/ {s+=$2} END {print s}' $cperfOutput)
awk '$1~/^[0-9]+/ {print "Homa '$workload $loadFactor'", $1, $2, '"\$2/$numMessages"', $4/$3, $6/$3}' $cperfOutput
