#!/bin/bash
# Usage: killserver kill_on_exit wd file
# First change to the working directory.
# If kill_on_exit == 1, only then clean up this server.

cd $2
file=$3
if [[ "$1" == "1" ]]; then
    # kill the server
    # extracting the pid as a substring of the file name - rcxx_pid
    pid=${file#*_}
    rm -rf logs/shm/$file

    command=`ps -o comm $pid | tail -n +2`
    while true; do
        if [ "$command" = "server" ]; then
            kill $pid 2>/dev/null || exit 0
        else
            # When we are starting the server using tools like time and perf,
            # only kill the children processes to allow the parent tool process
            # exit normally and produce its output.
            pkill -P $pid 2>/dev/null || exit 0
        fi
        sleep .01
    done
fi
